image: node:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

testing:
  stage: test
  services:
    - name: postgres:latest
      alias: db
  variables:
    POSTGRES_PASSWORD: postgres
    DB_HOST: db
    DB_PORT: 5432
  script:
    - echo "Testing..."
    - npm ci
    - npm run test


build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - npm ci
    - npm install -g typescript
    - tsc
    - echo "Compile complete."

lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - npm ci
    - npm install -g eslint
    - eslint -c .eslintrc.json --ext .ts,.js src/
    - echo "No lint issues found."

deploy-container-job:
  image: docker:19.03.12
  stage: deploy
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/psege/backend:latest .
    - docker push $CI_REGISTRY/psege/backend:latest