version: "3.9"
services:
  backend:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - frontend
      - backend

  db:
    image: postgres:13.5-alpine
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "db_data:/var/lib/postgresql/data"

networks:
  frontend:
    name: pse-frontend
    driver: bridge
  backend:
    name: pse-backend
    driver: bridge

volumes:
  db_data:
