version: "3.9" 
services:
  backend:
    build: .
    environment:
      - NODE_ENV=docker
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend

  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "db_data:/var/lib/postgresql/data"

networks:
  frontend:
    name: pse-frontend
    driver: bridge
  backend:
    name: pse-backend
    driver: bridge

volumes:
  db_data: 